package rest.mybatis.dao.eBillDao;

import java.util.List;

import rest.mybatis.model.eBillModel.AdvancesReceived;

public interface AdvancesReceivedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCES_RECEIVED
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCES_RECEIVED
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insert(AdvancesReceived record);

    int insertBatch(List list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCES_RECEIVED
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insertSelective(AdvancesReceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCES_RECEIVED
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    AdvancesReceived selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCES_RECEIVED
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKeySelective(AdvancesReceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCES_RECEIVED
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKey(AdvancesReceived record);
}