package rest.mybatis.dao.eBillDao;

import rest.mybatis.model.eBillModel.EbFoundsUseAmount;

public interface EbFoundsUseAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insert(EbFoundsUseAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insertSelective(EbFoundsUseAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    EbFoundsUseAmount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKeySelective(EbFoundsUseAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKey(EbFoundsUseAmount record);
}