package rest.mybatis.dao.eBillDao;

import java.util.List;
import java.util.Map;

import rest.mybatis.model.eBillModel.EbIssueT;
/**
 * 
 * @author 刘宗峰
 *
 */
public interface EbIssueTMapper extends EleBillMapper{
	
	/**
	 * @author 刘宗峰
	 * @return
	 */
	List<EbIssueT> searchUnClosed();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ISSUE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ISSUE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insert(EbIssueT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ISSUE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insertSelective(EbIssueT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ISSUE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    EbIssueT selectByPrimaryKey(String id);

    List<EbIssueT> selectIssueList();
    List<EbIssueT> queryIssueByMap(Map paramMap);
    @Override
    List<EbIssueT> queryListByPage(Map paramMap);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ISSUE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKeySelective(EbIssueT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ISSUE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKey(EbIssueT record);
}