package rest.mybatis.dao.eBillDao;

import rest.mybatis.model.eBillModel.EbNetAmount;

public interface EbNetAmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_NET_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_NET_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insert(EbNetAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_NET_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insertSelective(EbNetAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_NET_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    EbNetAmount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_NET_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKeySelective(EbNetAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_NET_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKey(EbNetAmount record);
}