package rest.mybatis.dao.eBillDao;

import rest.mybatis.model.eBillModel.EbRebateT;

public interface EbRebateTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_REBATE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_REBATE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insert(EbRebateT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_REBATE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int insertSelective(EbRebateT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_REBATE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    EbRebateT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_REBATE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKeySelective(EbRebateT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_REBATE_T
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    int updateByPrimaryKey(EbRebateT record);
}