package rest.mybatis.dao.eBillDao;

import java.util.List;

import rest.mybatis.model.eBillModel.EbSalesStatisticsT;
/**
 * 
 * @author 刘宗峰
 *
 */
public interface EbSalesStatisticsTMapper extends EleBillMapper{
	
	@Override
	int deleteBatch(List list);
	/**
     * @author 刘宗峰
     * @param list
     * @return
     */
	@Override
    int updateBatch(List list);
	/**
	 * @author 刘宗峰
	 * @TODO 查询对象集合
	 * @param issueId
	 * @return
	 */
	List<EbSalesStatisticsT> searchListByIssueId(String issueId);
	/**
	 * @author 刘宗峰
	 * @TODO 根据期数id 查询应收净额
	 * @param issueId
	 * @return
	 */
	int searchCountByIssueId(String issueId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int insert(EbSalesStatisticsT record);

    /**
     * @author 刘宗峰
     * @TODO 批量保存数据
     * @param list
     * @return
     */
    @Override
    int insertBatch(List list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int insertSelective(EbSalesStatisticsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    EbSalesStatisticsT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int updateByPrimaryKeySelective(EbSalesStatisticsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int updateByPrimaryKey(EbSalesStatisticsT record);
}