package rest.mybatis.dao.eBillDao;

import rest.mybatis.model.eBillModel.EbSalesStatisticsT;

public interface EbSalesStatisticsTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int insert(EbSalesStatisticsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int insertSelective(EbSalesStatisticsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    EbSalesStatisticsT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int updateByPrimaryKeySelective(EbSalesStatisticsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_SALES_STATISTICS_T
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    int updateByPrimaryKey(EbSalesStatisticsT record);
}