package rest.mybatis.model.eBillModel;

import java.util.Date;
/**
 * 预收款
 * @author 刘宗峰
 *
 */
public class AdvancesReceived {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String id;

    /**
     * @see 对账对象
     */
    private String reconciliationObj;

    /**
     * @see 收款类型
     */
    private String collectionType;

    /**
     * @see 收款单号
     */
    private String collectionNumber;

    /**
     * @see 收款日期
     */
    private Date collectionDays;

    /**
     * @see 币别
     */
    private String currency;

    /**
     * @see 汇率
     */
    private Double exchangeRate;

    /**
     * @see 客户
     */
    private String consumer;

    /**
     * @see 业务员
     */
    private String salesman;

    /**
     * @see 部门
     */
    private String department;

    /**
     * @see 预收款摘要 
     * 
     */
    private String advancesReceivedAbstract;

    /**
     * @see 收款金额
     */
    private Double collectionSum;

    /**
     * @see 未核销金额
     */
    private Double uncheckedSum;

    /**
     * @see 预收款操作人
     */
    private String advancesReceivedOperator;

    /**
     * @see 预收款操作日期
     */
    private Date advancesReceivedOperateDate;

    /**
     * @see 账单期数id
     */
    private String frIssueId;

    /**
     * @see 是否删除 默认1 ：0 删除，1未删除
     */
    private Integer advancesReceivedIsLive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ID
     *
     * @return the value of ADVANCES_RECEIVED.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ID
     *
     * @param id the value for ADVANCES_RECEIVED.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @return 对账对象
     *  对账对象
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReconciliationObj() {
        return reconciliationObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @param 对账对象
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReconciliationObj(String reconciliationObj) {
        this.reconciliationObj = reconciliationObj == null ? null : reconciliationObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @return 收款类型
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCollectionType() {
        return collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @param 收款类型
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionType(String collectionType) {
        this.collectionType = collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @return 收款单号
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCollectionNumber() {
        return collectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @param 收款单号
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionNumber(String collectionNumber) {
        this.collectionNumber = collectionNumber == null ? null : collectionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @return 收款日期
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getCollectionDays() {
        return collectionDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @param 收款日期
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionDays(Date collectionDays) {
        this.collectionDays = collectionDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.CURRENCY
     *
     * @return 币别
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.CURRENCY
     *
     * @param 币别
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @return 汇率
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @param 汇率
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setExchangeRate(Double exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.CONSUMER
     *
     * @return 客户
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.CONSUMER
     *
     * @param 客户
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer == null ? null : consumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.SALESMAN
     *
     * @return 业务员
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.SALESMAN
     *
     * @param 业务员
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.DEPARTMENT
     *
     * @return 部门
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.DEPARTMENT
     *
     * @param 部门
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @return 预收款摘要 
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getAdvancesReceivedAbstract() {
        return advancesReceivedAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @param 预收款摘要 
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedAbstract(String advancesReceivedAbstract) {
        this.advancesReceivedAbstract = advancesReceivedAbstract == null ? null : advancesReceivedAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @return 收款金额
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getCollectionSum() {
        return collectionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @param 收款金额
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionSum(Double collectionSum) {
        this.collectionSum = collectionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @return 未核销金额
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getUncheckedSum() {
        return uncheckedSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @param 未核销金额
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setUncheckedSum(Double uncheckedSum) {
        this.uncheckedSum = uncheckedSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @return 操作人
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getAdvancesReceivedOperator() {
        return advancesReceivedOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @param 操作人
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedOperator(String advancesReceivedOperator) {
        this.advancesReceivedOperator = advancesReceivedOperator == null ? null : advancesReceivedOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @return 操作时间
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getAdvancesReceivedOperateDate() {
        return advancesReceivedOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @param 操作时间
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedOperateDate(Date advancesReceivedOperateDate) {
        this.advancesReceivedOperateDate = advancesReceivedOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @return 期数ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getFrIssueId() {
        return frIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @param 期数id
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFrIssueId(String frIssueId) {
        this.frIssueId = frIssueId == null ? null : frIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @return 是否删除
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getAdvancesReceivedIsLive() {
        return advancesReceivedIsLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @param 是否删除
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedIsLive(Integer advancesReceivedIsLive) {
        this.advancesReceivedIsLive = advancesReceivedIsLive;
    }
}