package rest.mybatis.model.eBillModel;

import java.util.Date;
/**
 * 预收款
 * @author 刘宗峰
 *
 */
public class AdvancesReceived {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String reconciliationObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer collectionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String collectionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date collectionDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double exchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String consumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.SALESMAN
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.DEPARTMENT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String advancesReceivedAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double collectionSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double uncheckedSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String advancesReceivedOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date advancesReceivedOperateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String frIssueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer advancesReceivedIsLive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ID
     *
     * @return the value of ADVANCES_RECEIVED.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ID
     *
     * @param id the value for ADVANCES_RECEIVED.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @return the value of ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReconciliationObj() {
        return reconciliationObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @param reconciliationObj the value for ADVANCES_RECEIVED.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReconciliationObj(String reconciliationObj) {
        this.reconciliationObj = reconciliationObj == null ? null : reconciliationObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @return the value of ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getCollectionType() {
        return collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @param collectionType the value for ADVANCES_RECEIVED.COLLECTION_TYPE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionType(Integer collectionType) {
        this.collectionType = collectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @return the value of ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCollectionNumber() {
        return collectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @param collectionNumber the value for ADVANCES_RECEIVED.COLLECTION_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionNumber(String collectionNumber) {
        this.collectionNumber = collectionNumber == null ? null : collectionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @return the value of ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getCollectionDays() {
        return collectionDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @param collectionDays the value for ADVANCES_RECEIVED.COLLECTION_DAYS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionDays(Date collectionDays) {
        this.collectionDays = collectionDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.CURRENCY
     *
     * @return the value of ADVANCES_RECEIVED.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.CURRENCY
     *
     * @param currency the value for ADVANCES_RECEIVED.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @return the value of ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @param exchangeRate the value for ADVANCES_RECEIVED.EXCHANGE_RATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setExchangeRate(Double exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.CONSUMER
     *
     * @return the value of ADVANCES_RECEIVED.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.CONSUMER
     *
     * @param consumer the value for ADVANCES_RECEIVED.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer == null ? null : consumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.SALESMAN
     *
     * @return the value of ADVANCES_RECEIVED.SALESMAN
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.SALESMAN
     *
     * @param salesman the value for ADVANCES_RECEIVED.SALESMAN
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.DEPARTMENT
     *
     * @return the value of ADVANCES_RECEIVED.DEPARTMENT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.DEPARTMENT
     *
     * @param department the value for ADVANCES_RECEIVED.DEPARTMENT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @return the value of ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getAdvancesReceivedAbstract() {
        return advancesReceivedAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @param advancesReceivedAbstract the value for ADVANCES_RECEIVED.ADVANCES_RECEIVED_ABSTRACT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedAbstract(String advancesReceivedAbstract) {
        this.advancesReceivedAbstract = advancesReceivedAbstract == null ? null : advancesReceivedAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @return the value of ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getCollectionSum() {
        return collectionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @param collectionSum the value for ADVANCES_RECEIVED.COLLECTION_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCollectionSum(Double collectionSum) {
        this.collectionSum = collectionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @return the value of ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getUncheckedSum() {
        return uncheckedSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @param uncheckedSum the value for ADVANCES_RECEIVED.UNCHECKED_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setUncheckedSum(Double uncheckedSum) {
        this.uncheckedSum = uncheckedSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @return the value of ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getAdvancesReceivedOperator() {
        return advancesReceivedOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @param advancesReceivedOperator the value for ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedOperator(String advancesReceivedOperator) {
        this.advancesReceivedOperator = advancesReceivedOperator == null ? null : advancesReceivedOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @return the value of ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getAdvancesReceivedOperateDate() {
        return advancesReceivedOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @param advancesReceivedOperateDate the value for ADVANCES_RECEIVED.ADVANCES_RECEIVED_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedOperateDate(Date advancesReceivedOperateDate) {
        this.advancesReceivedOperateDate = advancesReceivedOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @return the value of ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getFrIssueId() {
        return frIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @param frIssueId the value for ADVANCES_RECEIVED.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFrIssueId(String frIssueId) {
        this.frIssueId = frIssueId == null ? null : frIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @return the value of ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getAdvancesReceivedIsLive() {
        return advancesReceivedIsLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @param advancesReceivedIsLive the value for ADVANCES_RECEIVED.ADVANCES_RECEIVED_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAdvancesReceivedIsLive(Integer advancesReceivedIsLive) {
        this.advancesReceivedIsLive = advancesReceivedIsLive;
    }
}