package rest.mybatis.model.eBillModel;

import java.util.Date;

public class EbFoundsUseAmount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.RETURN_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String returnNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.DURATION
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.RETURN_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.RETURN_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String returnRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String consumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String consignorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String reconciliationObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ORDER_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ORDER_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ISSUANCE_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String issuanceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ISSUANCE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date issuanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ORDER_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.INVOICED_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double invoicedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.BACK_LIB_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double backLibSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double rebateSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.SPECIAL_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double specialSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ORDER_REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double orderRebateSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.RETURN_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double returnAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ORDER_DISCOUNT_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double orderDiscountSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.TOTAL_AGENCY_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double totalAgencyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.SPECIAL_OFFER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double specialOffer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS_START
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date paymentDaysStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.AMOUNT_RECEIVABLE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double amountReceivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String paymentDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double foundsUseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.ORDER_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String orderRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.SALESMAN
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_INT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer serviceTypeInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_VARCHAR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String serviceTypeVarchar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.COMPANY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String frIssueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FOUNDS_USE_AMOUNT.IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer isLive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ID
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ID
     *
     * @param id the value for EB_FOUNDS_USE_AMOUNT.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_NUMBER
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.RETURN_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReturnNumber() {
        return returnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_NUMBER
     *
     * @param returnNumber the value for EB_FOUNDS_USE_AMOUNT.RETURN_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReturnNumber(String returnNumber) {
        this.returnNumber = returnNumber == null ? null : returnNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.DURATION
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.DURATION
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.DURATION
     *
     * @param duration the value for EB_FOUNDS_USE_AMOUNT.DURATION
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_DATE
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.RETURN_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_DATE
     *
     * @param returnDate the value for EB_FOUNDS_USE_AMOUNT.RETURN_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.CURRENCY
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.CURRENCY
     *
     * @param currency the value for EB_FOUNDS_USE_AMOUNT.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_REMARKS
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.RETURN_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReturnRemarks() {
        return returnRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_REMARKS
     *
     * @param returnRemarks the value for EB_FOUNDS_USE_AMOUNT.RETURN_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReturnRemarks(String returnRemarks) {
        this.returnRemarks = returnRemarks == null ? null : returnRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.CONSUMER
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.CONSUMER
     *
     * @param consumer the value for EB_FOUNDS_USE_AMOUNT.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer == null ? null : consumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.CONSIGNOR_NAME
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsignorName() {
        return consignorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.CONSIGNOR_NAME
     *
     * @param consignorName the value for EB_FOUNDS_USE_AMOUNT.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsignorName(String consignorName) {
        this.consignorName = consignorName == null ? null : consignorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.RECONCILIATION_OBJ
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReconciliationObj() {
        return reconciliationObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.RECONCILIATION_OBJ
     *
     * @param reconciliationObj the value for EB_FOUNDS_USE_AMOUNT.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReconciliationObj(String reconciliationObj) {
        this.reconciliationObj = reconciliationObj == null ? null : reconciliationObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_NUMBER
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ORDER_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_NUMBER
     *
     * @param orderNumber the value for EB_FOUNDS_USE_AMOUNT.ORDER_NUMBER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_DATE
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ORDER_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_DATE
     *
     * @param orderDate the value for EB_FOUNDS_USE_AMOUNT.ORDER_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ISSUANCE_NO
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ISSUANCE_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getIssuanceNo() {
        return issuanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ISSUANCE_NO
     *
     * @param issuanceNo the value for EB_FOUNDS_USE_AMOUNT.ISSUANCE_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssuanceNo(String issuanceNo) {
        this.issuanceNo = issuanceNo == null ? null : issuanceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ISSUANCE_DATE
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ISSUANCE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getIssuanceDate() {
        return issuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ISSUANCE_DATE
     *
     * @param issuanceDate the value for EB_FOUNDS_USE_AMOUNT.ISSUANCE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssuanceDate(Date issuanceDate) {
        this.issuanceDate = issuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_AMOUNT
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ORDER_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_AMOUNT
     *
     * @param orderAmount the value for EB_FOUNDS_USE_AMOUNT.ORDER_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.INVOICED_AMOUNT
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.INVOICED_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getInvoicedAmount() {
        return invoicedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.INVOICED_AMOUNT
     *
     * @param invoicedAmount the value for EB_FOUNDS_USE_AMOUNT.INVOICED_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setInvoicedAmount(Double invoicedAmount) {
        this.invoicedAmount = invoicedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.BACK_LIB_SUM
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.BACK_LIB_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getBackLibSum() {
        return backLibSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.BACK_LIB_SUM
     *
     * @param backLibSum the value for EB_FOUNDS_USE_AMOUNT.BACK_LIB_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setBackLibSum(Double backLibSum) {
        this.backLibSum = backLibSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.REBATE_SUM
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getRebateSum() {
        return rebateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.REBATE_SUM
     *
     * @param rebateSum the value for EB_FOUNDS_USE_AMOUNT.REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateSum(Double rebateSum) {
        this.rebateSum = rebateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.SPECIAL_SUM
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.SPECIAL_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getSpecialSum() {
        return specialSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.SPECIAL_SUM
     *
     * @param specialSum the value for EB_FOUNDS_USE_AMOUNT.SPECIAL_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSpecialSum(Double specialSum) {
        this.specialSum = specialSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_REBATE_SUM
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ORDER_REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getOrderRebateSum() {
        return orderRebateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_REBATE_SUM
     *
     * @param orderRebateSum the value for EB_FOUNDS_USE_AMOUNT.ORDER_REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderRebateSum(Double orderRebateSum) {
        this.orderRebateSum = orderRebateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_AMOUNT
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.RETURN_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getReturnAmount() {
        return returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.RETURN_AMOUNT
     *
     * @param returnAmount the value for EB_FOUNDS_USE_AMOUNT.RETURN_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReturnAmount(Double returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_DISCOUNT_SUM
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ORDER_DISCOUNT_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getOrderDiscountSum() {
        return orderDiscountSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_DISCOUNT_SUM
     *
     * @param orderDiscountSum the value for EB_FOUNDS_USE_AMOUNT.ORDER_DISCOUNT_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderDiscountSum(Double orderDiscountSum) {
        this.orderDiscountSum = orderDiscountSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.TOTAL_AGENCY_AMOUNT
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.TOTAL_AGENCY_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getTotalAgencyAmount() {
        return totalAgencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.TOTAL_AGENCY_AMOUNT
     *
     * @param totalAgencyAmount the value for EB_FOUNDS_USE_AMOUNT.TOTAL_AGENCY_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setTotalAgencyAmount(Double totalAgencyAmount) {
        this.totalAgencyAmount = totalAgencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.SPECIAL_OFFER
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.SPECIAL_OFFER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getSpecialOffer() {
        return specialOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.SPECIAL_OFFER
     *
     * @param specialOffer the value for EB_FOUNDS_USE_AMOUNT.SPECIAL_OFFER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSpecialOffer(Double specialOffer) {
        this.specialOffer = specialOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS_START
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS_START
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getPaymentDaysStart() {
        return paymentDaysStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS_START
     *
     * @param paymentDaysStart the value for EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS_START
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setPaymentDaysStart(Date paymentDaysStart) {
        this.paymentDaysStart = paymentDaysStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.AMOUNT_RECEIVABLE
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.AMOUNT_RECEIVABLE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getAmountReceivable() {
        return amountReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.AMOUNT_RECEIVABLE
     *
     * @param amountReceivable the value for EB_FOUNDS_USE_AMOUNT.AMOUNT_RECEIVABLE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAmountReceivable(Double amountReceivable) {
        this.amountReceivable = amountReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getPaymentDays() {
        return paymentDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS
     *
     * @param paymentDays the value for EB_FOUNDS_USE_AMOUNT.PAYMENT_DAYS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setPaymentDays(String paymentDays) {
        this.paymentDays = paymentDays == null ? null : paymentDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.FOUNDS_USE_AMOUNT
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getFoundsUseAmount() {
        return foundsUseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.FOUNDS_USE_AMOUNT
     *
     * @param foundsUseAmount the value for EB_FOUNDS_USE_AMOUNT.FOUNDS_USE_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFoundsUseAmount(Double foundsUseAmount) {
        this.foundsUseAmount = foundsUseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_REMARKS
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.ORDER_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getOrderRemarks() {
        return orderRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.ORDER_REMARKS
     *
     * @param orderRemarks the value for EB_FOUNDS_USE_AMOUNT.ORDER_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderRemarks(String orderRemarks) {
        this.orderRemarks = orderRemarks == null ? null : orderRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.SALESMAN
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.SALESMAN
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.SALESMAN
     *
     * @param salesman the value for EB_FOUNDS_USE_AMOUNT.SALESMAN
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_INT
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_INT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getServiceTypeInt() {
        return serviceTypeInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_INT
     *
     * @param serviceTypeInt the value for EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_INT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setServiceTypeInt(Integer serviceTypeInt) {
        this.serviceTypeInt = serviceTypeInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_VARCHAR
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_VARCHAR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getServiceTypeVarchar() {
        return serviceTypeVarchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_VARCHAR
     *
     * @param serviceTypeVarchar the value for EB_FOUNDS_USE_AMOUNT.SERVICE_TYPE_VARCHAR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setServiceTypeVarchar(String serviceTypeVarchar) {
        this.serviceTypeVarchar = serviceTypeVarchar == null ? null : serviceTypeVarchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.COMPANY
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.COMPANY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.COMPANY
     *
     * @param company the value for EB_FOUNDS_USE_AMOUNT.COMPANY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.OPERATOR
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.OPERATOR
     *
     * @param operator the value for EB_FOUNDS_USE_AMOUNT.OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.OPERATE_DATE
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.OPERATE_DATE
     *
     * @param operateDate the value for EB_FOUNDS_USE_AMOUNT.OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.FR_ISSUE_ID
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getFrIssueId() {
        return frIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.FR_ISSUE_ID
     *
     * @param frIssueId the value for EB_FOUNDS_USE_AMOUNT.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFrIssueId(String frIssueId) {
        this.frIssueId = frIssueId == null ? null : frIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FOUNDS_USE_AMOUNT.IS_LIVE
     *
     * @return the value of EB_FOUNDS_USE_AMOUNT.IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getIsLive() {
        return isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FOUNDS_USE_AMOUNT.IS_LIVE
     *
     * @param isLive the value for EB_FOUNDS_USE_AMOUNT.IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIsLive(Integer isLive) {
        this.isLive = isLive;
    }
}