package rest.mybatis.model.eBillModel;

import java.util.Date;

public class EbIssueT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String issueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_STATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer issueState; //0 未发布 ；1 发布； 2已关闭

    private Integer billState; //0 未核对；1核对
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_START_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date issueStartDate;
    private String issueStartDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_END_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date issueEndDate;
    private String issueEndDate1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_OPERATER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer issueOperater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date issueOperateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_ISSUE_T.ISSUE_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer issueIsLive; //是否删除： 0 删除， 1 未删除

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ID
     *
     * @return the value of EB_ISSUE_T.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ID
     *
     * @param id the value for EB_ISSUE_T.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_NAME
     *
     * @return the value of EB_ISSUE_T.ISSUE_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getIssueName() {
        return issueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_NAME
     *
     * @param issueName the value for EB_ISSUE_T.ISSUE_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueName(String issueName) {
        this.issueName = issueName == null ? null : issueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_STATE
     *
     * @return the value of EB_ISSUE_T.ISSUE_STATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getIssueState() {
        return issueState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_STATE
     *
     * @param issueState the value for EB_ISSUE_T.ISSUE_STATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueState(Integer issueState) {
        this.issueState = issueState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_START_DATE
     *
     * @return the value of EB_ISSUE_T.ISSUE_START_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getIssueStartDate() {
        return issueStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_START_DATE
     *
     * @param issueStartDate the value for EB_ISSUE_T.ISSUE_START_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueStartDate(Date issueStartDate) {
        this.issueStartDate = issueStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_END_DATE
     *
     * @return the value of EB_ISSUE_T.ISSUE_END_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getIssueEndDate() {
        return issueEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_END_DATE
     *
     * @param issueEndDate the value for EB_ISSUE_T.ISSUE_END_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueEndDate(Date issueEndDate) {
        this.issueEndDate = issueEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_OPERATER
     *
     * @return the value of EB_ISSUE_T.ISSUE_OPERATER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getIssueOperater() {
        return issueOperater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_OPERATER
     *
     * @param issueOperater the value for EB_ISSUE_T.ISSUE_OPERATER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueOperater(Integer issueOperater) {
        this.issueOperater = issueOperater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_OPERATE_DATE
     *
     * @return the value of EB_ISSUE_T.ISSUE_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getIssueOperateDate() {
        return issueOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_OPERATE_DATE
     *
     * @param issueOperateDate the value for EB_ISSUE_T.ISSUE_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueOperateDate(Date issueOperateDate) {
        this.issueOperateDate = issueOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_ISSUE_T.ISSUE_IS_LIVE
     *
     * @return the value of EB_ISSUE_T.ISSUE_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getIssueIsLive() {
        return issueIsLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_ISSUE_T.ISSUE_IS_LIVE
     *
     * @param issueIsLive the value for EB_ISSUE_T.ISSUE_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setIssueIsLive(Integer issueIsLive) {
        this.issueIsLive = issueIsLive;
    }

	public String getIssueEndDate1() {
		return issueEndDate1;
	}

	public void setIssueEndDate1(String issueEndDate1) {
		this.issueEndDate1 = issueEndDate1;
	}

	public String getIssueStartDate1() {
		return issueStartDate1;
	}

	public void setIssueStartDate1(String issueStartDate1) {
		this.issueStartDate1 = issueStartDate1;
	}

	public Integer getBillState() {
		return billState;
	}

	public void setBillState(Integer billState) {
		this.billState = billState;
	}
    
    
}