package rest.mybatis.model.eBillModel;

import java.util.Date;
/**
 * 
 * @author 刘宗峰
 *
 */
public class EbNetAmount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.ID
     *@see 应收净额表主键uuid
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.RECONCILIATION_OBJ
     *@see 对账对象
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String reconciliationObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.WORKER
     *@see 职员
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String worker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.SALES_ORDER_NO
     *@see 销售订单编号
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String salesOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.CONSUMER
     *@see 客户
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String consumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.BUILDING_USER
     *@see 使用单位
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String buildingUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.CONSIGNOR_NAME
     *@see 货主名称
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String consignorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.SYSTEM_ITEM
     *@see 系统项目
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String systemItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.ORDER_DATE
     *@see 订单日期
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.ORDER_SUM
     *@see 订单金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double orderSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.RECEIVED_PAYMENTS_SUM
     *@see 回款金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double receivedPaymentsSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.PERFORMANCE_GUARANTEE
     *@see 履约质保
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String performanceGuarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.BACK_LIB_SUM
     *@see 回库销账金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double backLibSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.SPECIAL_HANDING_SUM
     *@see 特殊处理金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double specialHandingSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.UNDELIVERY_SUM
     *@see 未发货金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double undeliverySum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.UNSETTLE_ACCOUNTS_SUM
     *@see 未结账款余额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double unsettleAccountsSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.INVOICE_CLASSFICATION
     *@see 发票分类
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String invoiceClassfication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.INVOICE_NO
     *@see 发票单号
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.FINISHED_INVOICE_SUM
     *@see 已开发票金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double finishedInvoiceSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.AGENCY_AMOUNT
     *@see 代理金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double agencyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.PROFIT_AMOUNT
     *@see 留利金额
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double profitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.CHECKED_ACCOUNT_REMARKS
     *@see 对账核实备注
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String checkedAccountRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.FINAL_DELIVERY_DATE
     * @see 最终发货日期
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date finalDeliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.CURRENCY
     *@see 货币
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.EXCHANGE_RATE
     *@see 汇率
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Double exchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.NET_AMOUNT_OPERATOR
     *@see 应收净额数据操作人
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer netAmountOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.NET_AMOUNT_OPERATE_DATE
     *@see 应收净额操作时间
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date netAmountOperateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.FR_ISSUE_ID
     *@see 账单期数id
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String frIssueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_NET_AMOUNT.NET_AMOUNT_IS_LIVE
     *@see 应收净额是否作废：1有效，0作废
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer netAmountIsLive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.ID
     *
     * @return the value of EB_NET_AMOUNT.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.ID
     *
     * @param id the value for EB_NET_AMOUNT.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.RECONCILIATION_OBJ
     *
     * @return the value of EB_NET_AMOUNT.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReconciliationObj() {
        return reconciliationObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.RECONCILIATION_OBJ
     *
     * @param reconciliationObj the value for EB_NET_AMOUNT.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReconciliationObj(String reconciliationObj) {
        this.reconciliationObj = reconciliationObj == null ? null : reconciliationObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.WORKER
     *
     * @return the value of EB_NET_AMOUNT.WORKER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.WORKER
     *
     * @param worker the value for EB_NET_AMOUNT.WORKER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setWorker(String worker) {
        this.worker = worker == null ? null : worker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.SALES_ORDER_NO
     *
     * @return the value of EB_NET_AMOUNT.SALES_ORDER_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getSalesOrderNo() {
        return salesOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.SALES_ORDER_NO
     *
     * @param salesOrderNo the value for EB_NET_AMOUNT.SALES_ORDER_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSalesOrderNo(String salesOrderNo) {
        this.salesOrderNo = salesOrderNo == null ? null : salesOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.CONSUMER
     *
     * @return the value of EB_NET_AMOUNT.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.CONSUMER
     *
     * @param consumer the value for EB_NET_AMOUNT.CONSUMER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer == null ? null : consumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.BUILDING_USER
     *
     * @return the value of EB_NET_AMOUNT.BUILDING_USER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getBuildingUser() {
        return buildingUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.BUILDING_USER
     *
     * @param buildingUser the value for EB_NET_AMOUNT.BUILDING_USER
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setBuildingUser(String buildingUser) {
        this.buildingUser = buildingUser == null ? null : buildingUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.CONSIGNOR_NAME
     *
     * @return the value of EB_NET_AMOUNT.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsignorName() {
        return consignorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.CONSIGNOR_NAME
     *
     * @param consignorName the value for EB_NET_AMOUNT.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsignorName(String consignorName) {
        this.consignorName = consignorName == null ? null : consignorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.SYSTEM_ITEM
     *
     * @return the value of EB_NET_AMOUNT.SYSTEM_ITEM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getSystemItem() {
        return systemItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.SYSTEM_ITEM
     *
     * @param systemItem the value for EB_NET_AMOUNT.SYSTEM_ITEM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSystemItem(String systemItem) {
        this.systemItem = systemItem == null ? null : systemItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.ORDER_DATE
     *
     * @return the value of EB_NET_AMOUNT.ORDER_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.ORDER_DATE
     *
     * @param orderDate the value for EB_NET_AMOUNT.ORDER_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.ORDER_SUM
     *
     * @return the value of EB_NET_AMOUNT.ORDER_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.ORDER_SUM
     *
     * @param orderSum the value for EB_NET_AMOUNT.ORDER_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setOrderSum(Double orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.RECEIVED_PAYMENTS_SUM
     *
     * @return the value of EB_NET_AMOUNT.RECEIVED_PAYMENTS_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getReceivedPaymentsSum() {
        return receivedPaymentsSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.RECEIVED_PAYMENTS_SUM
     *
     * @param receivedPaymentsSum the value for EB_NET_AMOUNT.RECEIVED_PAYMENTS_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReceivedPaymentsSum(Double receivedPaymentsSum) {
        this.receivedPaymentsSum = receivedPaymentsSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.PERFORMANCE_GUARANTEE
     *
     * @return the value of EB_NET_AMOUNT.PERFORMANCE_GUARANTEE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getPerformanceGuarantee() {
        return performanceGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.PERFORMANCE_GUARANTEE
     *
     * @param performanceGuarantee the value for EB_NET_AMOUNT.PERFORMANCE_GUARANTEE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setPerformanceGuarantee(String performanceGuarantee) {
        this.performanceGuarantee = performanceGuarantee == null ? null : performanceGuarantee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.BACK_LIB_SUM
     *
     * @return the value of EB_NET_AMOUNT.BACK_LIB_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getBackLibSum() {
        return backLibSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.BACK_LIB_SUM
     *
     * @param backLibSum the value for EB_NET_AMOUNT.BACK_LIB_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setBackLibSum(Double backLibSum) {
        this.backLibSum = backLibSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.SPECIAL_HANDING_SUM
     *
     * @return the value of EB_NET_AMOUNT.SPECIAL_HANDING_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getSpecialHandingSum() {
        return specialHandingSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.SPECIAL_HANDING_SUM
     *
     * @param specialHandingSum the value for EB_NET_AMOUNT.SPECIAL_HANDING_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSpecialHandingSum(Double specialHandingSum) {
        this.specialHandingSum = specialHandingSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.UNDELIVERY_SUM
     *
     * @return the value of EB_NET_AMOUNT.UNDELIVERY_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getUndeliverySum() {
        return undeliverySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.UNDELIVERY_SUM
     *
     * @param undeliverySum the value for EB_NET_AMOUNT.UNDELIVERY_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setUndeliverySum(Double undeliverySum) {
        this.undeliverySum = undeliverySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.UNSETTLE_ACCOUNTS_SUM
     *
     * @return the value of EB_NET_AMOUNT.UNSETTLE_ACCOUNTS_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getUnsettleAccountsSum() {
        return unsettleAccountsSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.UNSETTLE_ACCOUNTS_SUM
     *
     * @param unsettleAccountsSum the value for EB_NET_AMOUNT.UNSETTLE_ACCOUNTS_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setUnsettleAccountsSum(Double unsettleAccountsSum) {
        this.unsettleAccountsSum = unsettleAccountsSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.INVOICE_CLASSFICATION
     *
     * @return the value of EB_NET_AMOUNT.INVOICE_CLASSFICATION
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getInvoiceClassfication() {
        return invoiceClassfication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.INVOICE_CLASSFICATION
     *
     * @param invoiceClassfication the value for EB_NET_AMOUNT.INVOICE_CLASSFICATION
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setInvoiceClassfication(String invoiceClassfication) {
        this.invoiceClassfication = invoiceClassfication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.INVOICE_NO
     *
     * @return the value of EB_NET_AMOUNT.INVOICE_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.INVOICE_NO
     *
     * @param invoiceNo the value for EB_NET_AMOUNT.INVOICE_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.FINISHED_INVOICE_SUM
     *
     * @return the value of EB_NET_AMOUNT.FINISHED_INVOICE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getFinishedInvoiceSum() {
        return finishedInvoiceSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.FINISHED_INVOICE_SUM
     *
     * @param finishedInvoiceSum the value for EB_NET_AMOUNT.FINISHED_INVOICE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFinishedInvoiceSum(Double finishedInvoiceSum) {
        this.finishedInvoiceSum = finishedInvoiceSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.AGENCY_AMOUNT
     *
     * @return the value of EB_NET_AMOUNT.AGENCY_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getAgencyAmount() {
        return agencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.AGENCY_AMOUNT
     *
     * @param agencyAmount the value for EB_NET_AMOUNT.AGENCY_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setAgencyAmount(Double agencyAmount) {
        this.agencyAmount = agencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.PROFIT_AMOUNT
     *
     * @return the value of EB_NET_AMOUNT.PROFIT_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getProfitAmount() {
        return profitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.PROFIT_AMOUNT
     *
     * @param profitAmount the value for EB_NET_AMOUNT.PROFIT_AMOUNT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setProfitAmount(Double profitAmount) {
        this.profitAmount = profitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.CHECKED_ACCOUNT_REMARKS
     *
     * @return the value of EB_NET_AMOUNT.CHECKED_ACCOUNT_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCheckedAccountRemarks() {
        return checkedAccountRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.CHECKED_ACCOUNT_REMARKS
     *
     * @param checkedAccountRemarks the value for EB_NET_AMOUNT.CHECKED_ACCOUNT_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCheckedAccountRemarks(String checkedAccountRemarks) {
        this.checkedAccountRemarks = checkedAccountRemarks == null ? null : checkedAccountRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.FINAL_DELIVERY_DATE
     *
     * @return the value of EB_NET_AMOUNT.FINAL_DELIVERY_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getFinalDeliveryDate() {
        return finalDeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.FINAL_DELIVERY_DATE
     *
     * @param finalDeliveryDate the value for EB_NET_AMOUNT.FINAL_DELIVERY_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFinalDeliveryDate(Date finalDeliveryDate) {
        this.finalDeliveryDate = finalDeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.CURRENCY
     *
     * @return the value of EB_NET_AMOUNT.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.CURRENCY
     *
     * @param currency the value for EB_NET_AMOUNT.CURRENCY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.EXCHANGE_RATE
     *
     * @return the value of EB_NET_AMOUNT.EXCHANGE_RATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Double getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.EXCHANGE_RATE
     *
     * @param exchangeRate the value for EB_NET_AMOUNT.EXCHANGE_RATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setExchangeRate(Double exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.NET_AMOUNT_OPERATOR
     *
     * @return the value of EB_NET_AMOUNT.NET_AMOUNT_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getNetAmountOperator() {
        return netAmountOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.NET_AMOUNT_OPERATOR
     *
     * @param netAmountOperator the value for EB_NET_AMOUNT.NET_AMOUNT_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setNetAmountOperator(Integer netAmountOperator) {
        this.netAmountOperator = netAmountOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.NET_AMOUNT_OPERATE_DATE
     *
     * @return the value of EB_NET_AMOUNT.NET_AMOUNT_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getNetAmountOperateDate() {
        return netAmountOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.NET_AMOUNT_OPERATE_DATE
     *
     * @param netAmountOperateDate the value for EB_NET_AMOUNT.NET_AMOUNT_OPERATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setNetAmountOperateDate(Date netAmountOperateDate) {
        this.netAmountOperateDate = netAmountOperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.FR_ISSUE_ID
     *
     * @return the value of EB_NET_AMOUNT.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getFrIssueId() {
        return frIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.FR_ISSUE_ID
     *
     * @param frIssueId the value for EB_NET_AMOUNT.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFrIssueId(String frIssueId) {
        this.frIssueId = frIssueId == null ? null : frIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_NET_AMOUNT.NET_AMOUNT_IS_LIVE
     *
     * @return the value of EB_NET_AMOUNT.NET_AMOUNT_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getNetAmountIsLive() {
        return netAmountIsLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_NET_AMOUNT.NET_AMOUNT_IS_LIVE
     *
     * @param netAmountIsLive the value for EB_NET_AMOUNT.NET_AMOUNT_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setNetAmountIsLive(Integer netAmountIsLive) {
        this.netAmountIsLive = netAmountIsLive;
    }
}