package rest.mybatis.model.eBillModel;

import java.util.Date;

public class EbRebateT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String reconciliationObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_NOTICE_BILL_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String rebateNoticeBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.SALES_ORDER_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String salesOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date rebateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_ABSTRACT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String rebateAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String consignorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String rebateSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_PROPERTY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String rebateProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String rebateRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer rebateOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_OPERAT_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Date rebateOperatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.REBATE_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private Integer rebateIsLive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_REBATE_T.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    private String frIssueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.ID
     *
     * @return the value of EB_REBATE_T.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.ID
     *
     * @param id the value for EB_REBATE_T.ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.RECONCILIATION_OBJ
     *
     * @return the value of EB_REBATE_T.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getReconciliationObj() {
        return reconciliationObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.RECONCILIATION_OBJ
     *
     * @param reconciliationObj the value for EB_REBATE_T.RECONCILIATION_OBJ
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setReconciliationObj(String reconciliationObj) {
        this.reconciliationObj = reconciliationObj == null ? null : reconciliationObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_NOTICE_BILL_NO
     *
     * @return the value of EB_REBATE_T.REBATE_NOTICE_BILL_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getRebateNoticeBillNo() {
        return rebateNoticeBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_NOTICE_BILL_NO
     *
     * @param rebateNoticeBillNo the value for EB_REBATE_T.REBATE_NOTICE_BILL_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateNoticeBillNo(String rebateNoticeBillNo) {
        this.rebateNoticeBillNo = rebateNoticeBillNo == null ? null : rebateNoticeBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.SALES_ORDER_NO
     *
     * @return the value of EB_REBATE_T.SALES_ORDER_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getSalesOrderNo() {
        return salesOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.SALES_ORDER_NO
     *
     * @param salesOrderNo the value for EB_REBATE_T.SALES_ORDER_NO
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setSalesOrderNo(String salesOrderNo) {
        this.salesOrderNo = salesOrderNo == null ? null : salesOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_DATE
     *
     * @return the value of EB_REBATE_T.REBATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getRebateDate() {
        return rebateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_DATE
     *
     * @param rebateDate the value for EB_REBATE_T.REBATE_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateDate(Date rebateDate) {
        this.rebateDate = rebateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_ABSTRACT
     *
     * @return the value of EB_REBATE_T.REBATE_ABSTRACT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getRebateAbstract() {
        return rebateAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_ABSTRACT
     *
     * @param rebateAbstract the value for EB_REBATE_T.REBATE_ABSTRACT
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateAbstract(String rebateAbstract) {
        this.rebateAbstract = rebateAbstract == null ? null : rebateAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.CONSIGNOR_NAME
     *
     * @return the value of EB_REBATE_T.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getConsignorName() {
        return consignorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.CONSIGNOR_NAME
     *
     * @param consignorName the value for EB_REBATE_T.CONSIGNOR_NAME
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setConsignorName(String consignorName) {
        this.consignorName = consignorName == null ? null : consignorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_SUM
     *
     * @return the value of EB_REBATE_T.REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getRebateSum() {
        return rebateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_SUM
     *
     * @param rebateSum the value for EB_REBATE_T.REBATE_SUM
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateSum(String rebateSum) {
        this.rebateSum = rebateSum == null ? null : rebateSum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_PROPERTY
     *
     * @return the value of EB_REBATE_T.REBATE_PROPERTY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getRebateProperty() {
        return rebateProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_PROPERTY
     *
     * @param rebateProperty the value for EB_REBATE_T.REBATE_PROPERTY
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateProperty(String rebateProperty) {
        this.rebateProperty = rebateProperty == null ? null : rebateProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_REMARKS
     *
     * @return the value of EB_REBATE_T.REBATE_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getRebateRemarks() {
        return rebateRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_REMARKS
     *
     * @param rebateRemarks the value for EB_REBATE_T.REBATE_REMARKS
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateRemarks(String rebateRemarks) {
        this.rebateRemarks = rebateRemarks == null ? null : rebateRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_OPERATOR
     *
     * @return the value of EB_REBATE_T.REBATE_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getRebateOperator() {
        return rebateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_OPERATOR
     *
     * @param rebateOperator the value for EB_REBATE_T.REBATE_OPERATOR
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateOperator(Integer rebateOperator) {
        this.rebateOperator = rebateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_OPERAT_DATE
     *
     * @return the value of EB_REBATE_T.REBATE_OPERAT_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Date getRebateOperatDate() {
        return rebateOperatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_OPERAT_DATE
     *
     * @param rebateOperatDate the value for EB_REBATE_T.REBATE_OPERAT_DATE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateOperatDate(Date rebateOperatDate) {
        this.rebateOperatDate = rebateOperatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.REBATE_IS_LIVE
     *
     * @return the value of EB_REBATE_T.REBATE_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public Integer getRebateIsLive() {
        return rebateIsLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.REBATE_IS_LIVE
     *
     * @param rebateIsLive the value for EB_REBATE_T.REBATE_IS_LIVE
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setRebateIsLive(Integer rebateIsLive) {
        this.rebateIsLive = rebateIsLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_REBATE_T.FR_ISSUE_ID
     *
     * @return the value of EB_REBATE_T.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public String getFrIssueId() {
        return frIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_REBATE_T.FR_ISSUE_ID
     *
     * @param frIssueId the value for EB_REBATE_T.FR_ISSUE_ID
     *
     * @mbggenerated Fri Sep 22 14:09:36 CST 2017
     */
    public void setFrIssueId(String frIssueId) {
        this.frIssueId = frIssueId == null ? null : frIssueId.trim();
    }
}