package rest.mybatis.model.eBillModel;

import java.util.Date;
/**
 * 
 * @author 刘宗峰
 *
 */
public class EbSalesStatisticsT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.ID
     *@see 销售业务统计总表主键uuid
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.DATA_TYPE
     *@see 数据分类
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.ORDER_NO
     *@see 销售订单编号
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.ORDER_DETAIL_NO
     *@see 订单明细编号
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String orderDetailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.ORDER_LINE_NO
     *@see 订单行号
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Integer orderLineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.ORDER_DATE
     *@see 订单日期
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.PURCHASE_UNITS
     *@see 购货单位
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String purchaseUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.MATERIAL_CODE
     *@see 物料编码
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.MATERIAL_NAME
     *@see 物料名称
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SPEC_TYP
     *@see 规格型号
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String specTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.CURRENCY_CODE
     *@see 货币内码
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String currencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.EXCHANGE_RATE
     *@see 汇率
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double exchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.ORDER_NUM
     *@see 订货数量
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double orderNum;
    
    /**
     * 订货金额
     */
    private Double orderAmount;
   
    


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.AGENCY_AMOUNT
     *@see 代理金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double agencyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.BUSINESS_NO
     *@see 业务单号
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String businessNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.BUSINESS_DATE
     *@see 业务日期
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Date businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SEND_NUM
     *@see 发货数量
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double sendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SEND_AMOUNT
     *@see 发货金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double sendAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.INVOICE_NUM
     *@see 发票数量
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double invoiceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.INVOICE_AMOUNT
     *@see 发票金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double invoiceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.PAYLIBARY_AMOUNT
     *@see 回库销账金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double paylibaryAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SPECIAL_AMOUNT
     *@see 特殊销账金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double specialAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.REBATE_AMOUNT
     *@see 留返利销账金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double rebateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.PAYMENT_AMOUNT
     *@see 回款销账金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double paymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.PERFORMANCE
     *@see 履约质保
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double performance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.PROFIT_AMOUNT
     *@see 留利金额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double profitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.RECEIVABLE_AMOUNT
     *@see 应收余额
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Double receivableAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SHIPPER_NAME
     *@see 货主名称
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String shipperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SERVICE_TYPE
     *@see 业务类型
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.RECONCILIATION_OBJ
     *@see 对账对象
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String reconciliationObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.WORKER
     *@see 职员
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String worker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.DEPT
     *@see 部门
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.DEPT_ID
     *@see 部门id 备用
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.AREA
     *@see 区域
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SYS_PROJECT
     *@see 系统项目名称
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String sysProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.SYS_PROJECTID
     *@see 系统项目id备用
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String sysProjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.REMARKS
     *@see 备注 
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.CHANGE_REMARKS
     *@see 修改备注
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String changeRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.USE_UNIT
     *@see 使用单位
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String useUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.VIPDEPT
     *@see VIP部门
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String vipdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.VIPDEPT_MANAGE
     *@see VIP部门经理
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String vipdeptManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.VIPDEPT_MANAGEID
     *@see 部门经理用户id
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Integer vipdeptManageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.TRADE
     *@see 行业
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String trade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.PLIN
     *@see 产品线
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String plin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.END_SEND_DATE
     *@see 最后发货日期
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private Date endSendDate;

    /**
     * 操作人
     */
    private Integer operator;
    /**
     * 操作时间
     */
    private Date operateDate;
    /**
     * 是否有效：1有效，0无效
     */
    private Integer isLive;
    /**
     * 外键：期数id
     */
    private String frIssueId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_SALES_STATISTICS_T.TEXT1
     *@see
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    private String text1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.ID
     *
     * @return the value of EB_SALES_STATISTICS_T.ID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.ID
     *
     * @param id the value for EB_SALES_STATISTICS_T.ID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.DATA_TYPE
     *
     * @return the value of EB_SALES_STATISTICS_T.DATA_TYPE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.DATA_TYPE
     *
     * @param dataType the value for EB_SALES_STATISTICS_T.DATA_TYPE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.ORDER_NO
     *
     * @return the value of EB_SALES_STATISTICS_T.ORDER_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.ORDER_NO
     *
     * @param orderNo the value for EB_SALES_STATISTICS_T.ORDER_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.ORDER_DETAIL_NO
     *
     * @return the value of EB_SALES_STATISTICS_T.ORDER_DETAIL_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getOrderDetailNo() {
        return orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.ORDER_DETAIL_NO
     *
     * @param orderDetailNo the value for EB_SALES_STATISTICS_T.ORDER_DETAIL_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setOrderDetailNo(String orderDetailNo) {
        this.orderDetailNo = orderDetailNo == null ? null : orderDetailNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.ORDER_LINE_NO
     *
     * @return the value of EB_SALES_STATISTICS_T.ORDER_LINE_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Integer getOrderLineNo() {
        return orderLineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.ORDER_LINE_NO
     *
     * @param orderLineNo the value for EB_SALES_STATISTICS_T.ORDER_LINE_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setOrderLineNo(Integer orderLineNo) {
        this.orderLineNo = orderLineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.ORDER_DATE
     *
     * @return the value of EB_SALES_STATISTICS_T.ORDER_DATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.ORDER_DATE
     *
     * @param orderDate the value for EB_SALES_STATISTICS_T.ORDER_DATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.PURCHASE_UNITS
     *
     * @return the value of EB_SALES_STATISTICS_T.PURCHASE_UNITS
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getPurchaseUnits() {
        return purchaseUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.PURCHASE_UNITS
     *
     * @param purchaseUnits the value for EB_SALES_STATISTICS_T.PURCHASE_UNITS
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setPurchaseUnits(String purchaseUnits) {
        this.purchaseUnits = purchaseUnits == null ? null : purchaseUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.MATERIAL_CODE
     *
     * @return the value of EB_SALES_STATISTICS_T.MATERIAL_CODE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.MATERIAL_CODE
     *
     * @param materialCode the value for EB_SALES_STATISTICS_T.MATERIAL_CODE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.MATERIAL_NAME
     *
     * @return the value of EB_SALES_STATISTICS_T.MATERIAL_NAME
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.MATERIAL_NAME
     *
     * @param materialName the value for EB_SALES_STATISTICS_T.MATERIAL_NAME
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SPEC_TYP
     *
     * @return the value of EB_SALES_STATISTICS_T.SPEC_TYP
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getSpecTyp() {
        return specTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SPEC_TYP
     *
     * @param specTyp the value for EB_SALES_STATISTICS_T.SPEC_TYP
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setSpecTyp(String specTyp) {
        this.specTyp = specTyp == null ? null : specTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.CURRENCY_CODE
     *
     * @return the value of EB_SALES_STATISTICS_T.CURRENCY_CODE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.CURRENCY_CODE
     *
     * @param currencyCode the value for EB_SALES_STATISTICS_T.CURRENCY_CODE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.EXCHANGE_RATE
     *
     * @return the value of EB_SALES_STATISTICS_T.EXCHANGE_RATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.EXCHANGE_RATE
     *
     * @param exchangeRate the value for EB_SALES_STATISTICS_T.EXCHANGE_RATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setExchangeRate(Double exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.ORDER_NUM
     *
     * @return the value of EB_SALES_STATISTICS_T.ORDER_NUM
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.ORDER_NUM
     *
     * @param orderNum the value for EB_SALES_STATISTICS_T.ORDER_NUM
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setOrderNum(Double orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.AGENCY_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.AGENCY_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getAgencyAmount() {
        return agencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.AGENCY_AMOUNT
     *
     * @param agencyAmount the value for EB_SALES_STATISTICS_T.AGENCY_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setAgencyAmount(Double agencyAmount) {
        this.agencyAmount = agencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.BUSINESS_NO
     *
     * @return the value of EB_SALES_STATISTICS_T.BUSINESS_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getBusinessNo() {
        return businessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.BUSINESS_NO
     *
     * @param businessNo the value for EB_SALES_STATISTICS_T.BUSINESS_NO
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo == null ? null : businessNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.BUSINESS_DATE
     *
     * @return the value of EB_SALES_STATISTICS_T.BUSINESS_DATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Date getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.BUSINESS_DATE
     *
     * @param businessDate the value for EB_SALES_STATISTICS_T.BUSINESS_DATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setBusinessDate(Date businessDate) {
        this.businessDate = businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SEND_NUM
     *
     * @return the value of EB_SALES_STATISTICS_T.SEND_NUM
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getSendNum() {
        return sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SEND_NUM
     *
     * @param sendNum the value for EB_SALES_STATISTICS_T.SEND_NUM
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setSendNum(Double sendNum) {
        this.sendNum = sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SEND_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.SEND_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getSendAmount() {
        return sendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SEND_AMOUNT
     *
     * @param sendAmount the value for EB_SALES_STATISTICS_T.SEND_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setSendAmount(Double sendAmount) {
        this.sendAmount = sendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.INVOICE_NUM
     *
     * @return the value of EB_SALES_STATISTICS_T.INVOICE_NUM
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getInvoiceNum() {
        return invoiceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.INVOICE_NUM
     *
     * @param invoiceNum the value for EB_SALES_STATISTICS_T.INVOICE_NUM
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setInvoiceNum(Double invoiceNum) {
        this.invoiceNum = invoiceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.INVOICE_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.INVOICE_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.INVOICE_AMOUNT
     *
     * @param invoiceAmount the value for EB_SALES_STATISTICS_T.INVOICE_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setInvoiceAmount(Double invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.PAYLIBARY_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.PAYLIBARY_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getPaylibaryAmount() {
        return paylibaryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.PAYLIBARY_AMOUNT
     *
     * @param paylibaryAmount the value for EB_SALES_STATISTICS_T.PAYLIBARY_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setPaylibaryAmount(Double paylibaryAmount) {
        this.paylibaryAmount = paylibaryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SPECIAL_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.SPECIAL_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getSpecialAmount() {
        return specialAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SPECIAL_AMOUNT
     *
     * @param specialAmount the value for EB_SALES_STATISTICS_T.SPECIAL_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setSpecialAmount(Double specialAmount) {
        this.specialAmount = specialAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.REBATE_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.REBATE_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getRebateAmount() {
        return rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.REBATE_AMOUNT
     *
     * @param rebateAmount the value for EB_SALES_STATISTICS_T.REBATE_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setRebateAmount(Double rebateAmount) {
        this.rebateAmount = rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.PAYMENT_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.PAYMENT_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.PAYMENT_AMOUNT
     *
     * @param paymentAmount the value for EB_SALES_STATISTICS_T.PAYMENT_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setPaymentAmount(Double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.PERFORMANCE
     *
     * @return the value of EB_SALES_STATISTICS_T.PERFORMANCE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.PERFORMANCE
     *
     * @param performance the value for EB_SALES_STATISTICS_T.PERFORMANCE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setPerformance(Double performance) {
        this.performance = performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.PROFIT_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.PROFIT_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getProfitAmount() {
        return profitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.PROFIT_AMOUNT
     *
     * @param profitAmount the value for EB_SALES_STATISTICS_T.PROFIT_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setProfitAmount(Double profitAmount) {
        this.profitAmount = profitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.RECEIVABLE_AMOUNT
     *
     * @return the value of EB_SALES_STATISTICS_T.RECEIVABLE_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Double getReceivableAmount() {
        return receivableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.RECEIVABLE_AMOUNT
     *
     * @param receivableAmount the value for EB_SALES_STATISTICS_T.RECEIVABLE_AMOUNT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setReceivableAmount(Double receivableAmount) {
        this.receivableAmount = receivableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SHIPPER_NAME
     *
     * @return the value of EB_SALES_STATISTICS_T.SHIPPER_NAME
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getShipperName() {
        return shipperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SHIPPER_NAME
     *
     * @param shipperName the value for EB_SALES_STATISTICS_T.SHIPPER_NAME
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setShipperName(String shipperName) {
        this.shipperName = shipperName == null ? null : shipperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SERVICE_TYPE
     *
     * @return the value of EB_SALES_STATISTICS_T.SERVICE_TYPE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SERVICE_TYPE
     *
     * @param serviceType the value for EB_SALES_STATISTICS_T.SERVICE_TYPE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.RECONCILIATION_OBJ
     *
     * @return the value of EB_SALES_STATISTICS_T.RECONCILIATION_OBJ
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getReconciliationObj() {
        return reconciliationObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.RECONCILIATION_OBJ
     *
     * @param reconciliationObj the value for EB_SALES_STATISTICS_T.RECONCILIATION_OBJ
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setReconciliationObj(String reconciliationObj) {
        this.reconciliationObj = reconciliationObj == null ? null : reconciliationObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.WORKER
     *
     * @return the value of EB_SALES_STATISTICS_T.WORKER
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.WORKER
     *
     * @param worker the value for EB_SALES_STATISTICS_T.WORKER
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setWorker(String worker) {
        this.worker = worker == null ? null : worker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.DEPT
     *
     * @return the value of EB_SALES_STATISTICS_T.DEPT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.DEPT
     *
     * @param dept the value for EB_SALES_STATISTICS_T.DEPT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.DEPT_ID
     *
     * @return the value of EB_SALES_STATISTICS_T.DEPT_ID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.DEPT_ID
     *
     * @param deptId the value for EB_SALES_STATISTICS_T.DEPT_ID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.AREA
     *
     * @return the value of EB_SALES_STATISTICS_T.AREA
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.AREA
     *
     * @param area the value for EB_SALES_STATISTICS_T.AREA
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SYS_PROJECT
     *
     * @return the value of EB_SALES_STATISTICS_T.SYS_PROJECT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getSysProject() {
        return sysProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SYS_PROJECT
     *
     * @param sysProject the value for EB_SALES_STATISTICS_T.SYS_PROJECT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setSysProject(String sysProject) {
        this.sysProject = sysProject == null ? null : sysProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.SYS_PROJECTID
     *
     * @return the value of EB_SALES_STATISTICS_T.SYS_PROJECTID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getSysProjectid() {
        return sysProjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.SYS_PROJECTID
     *
     * @param sysProjectid the value for EB_SALES_STATISTICS_T.SYS_PROJECTID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setSysProjectid(String sysProjectid) {
        this.sysProjectid = sysProjectid == null ? null : sysProjectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.REMARKS
     *
     * @return the value of EB_SALES_STATISTICS_T.REMARKS
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.REMARKS
     *
     * @param remarks the value for EB_SALES_STATISTICS_T.REMARKS
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.CHANGE_REMARKS
     *
     * @return the value of EB_SALES_STATISTICS_T.CHANGE_REMARKS
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getChangeRemarks() {
        return changeRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.CHANGE_REMARKS
     *
     * @param changeRemarks the value for EB_SALES_STATISTICS_T.CHANGE_REMARKS
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setChangeRemarks(String changeRemarks) {
        this.changeRemarks = changeRemarks == null ? null : changeRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.USE_UNIT
     *
     * @return the value of EB_SALES_STATISTICS_T.USE_UNIT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getUseUnit() {
        return useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.USE_UNIT
     *
     * @param useUnit the value for EB_SALES_STATISTICS_T.USE_UNIT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setUseUnit(String useUnit) {
        this.useUnit = useUnit == null ? null : useUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.VIPDEPT
     *
     * @return the value of EB_SALES_STATISTICS_T.VIPDEPT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getVipdept() {
        return vipdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.VIPDEPT
     *
     * @param vipdept the value for EB_SALES_STATISTICS_T.VIPDEPT
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setVipdept(String vipdept) {
        this.vipdept = vipdept == null ? null : vipdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.VIPDEPT_MANAGE
     *
     * @return the value of EB_SALES_STATISTICS_T.VIPDEPT_MANAGE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getVipdeptManage() {
        return vipdeptManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.VIPDEPT_MANAGE
     *
     * @param vipdeptManage the value for EB_SALES_STATISTICS_T.VIPDEPT_MANAGE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setVipdeptManage(String vipdeptManage) {
        this.vipdeptManage = vipdeptManage == null ? null : vipdeptManage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.VIPDEPT_MANAGEID
     *
     * @return the value of EB_SALES_STATISTICS_T.VIPDEPT_MANAGEID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Integer getVipdeptManageid() {
        return vipdeptManageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.VIPDEPT_MANAGEID
     *
     * @param vipdeptManageid the value for EB_SALES_STATISTICS_T.VIPDEPT_MANAGEID
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setVipdeptManageid(Integer vipdeptManageid) {
        this.vipdeptManageid = vipdeptManageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.TRADE
     *
     * @return the value of EB_SALES_STATISTICS_T.TRADE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.TRADE
     *
     * @param trade the value for EB_SALES_STATISTICS_T.TRADE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.PLIN
     *
     * @return the value of EB_SALES_STATISTICS_T.PLIN
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getPlin() {
        return plin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.PLIN
     *
     * @param plin the value for EB_SALES_STATISTICS_T.PLIN
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setPlin(String plin) {
        this.plin = plin == null ? null : plin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.END_SEND_DATE
     *
     * @return the value of EB_SALES_STATISTICS_T.END_SEND_DATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public Date getEndSendDate() {
        return endSendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.END_SEND_DATE
     *
     * @param endSendDate the value for EB_SALES_STATISTICS_T.END_SEND_DATE
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setEndSendDate(Date endSendDate) {
        this.endSendDate = endSendDate;
    }


    public Double getOrderAmount() {
		return orderAmount;
	}

	public void setOrderAmount(Double orderAmount) {
		this.orderAmount = orderAmount;
	}

	public Integer getOperator() {
		return operator;
	}

	public void setOperator(Integer operator) {
		this.operator = operator;
	}

	public Date getOperateDate() {
		return operateDate;
	}

	public void setOperateDate(Date operateDate) {
		this.operateDate = operateDate;
	}

	public Integer getIsLive() {
		return isLive;
	}

	public void setIsLive(Integer isLive) {
		this.isLive = isLive;
	}
	
	
    public String getFrIssueId() {
		return frIssueId;
	}

	public void setFrIssueId(String frIssueId) {
		this.frIssueId = frIssueId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_SALES_STATISTICS_T.TEXT1
     *
     * @return the value of EB_SALES_STATISTICS_T.TEXT1
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public String getText1() {
        return text1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_SALES_STATISTICS_T.TEXT1
     *
     * @param text1 the value for EB_SALES_STATISTICS_T.TEXT1
     *
     * @mbggenerated Wed Nov 08 17:24:07 CST 2017
     */
    public void setText1(String text1) {
        this.text1 = text1 == null ? null : text1.trim();
    }
}