package rest.mybatis.dao.misDao;

import rest.mybatis.model.misModel.TResources;

public interface TResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    int insert(TResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    int insertSelective(TResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    TResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    int updateByPrimaryKeySelective(TResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_RESOURCES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    int updateByPrimaryKey(TResources record);
}