package rest.mybatis.dao.misDao;

import java.util.List;

import rest.mybatis.model.misModel.TUserResources;

public interface TUserResourcesMapper {
	/**
	 * @TODO 根据工号查询权限关系表
	 * @author 刘宗峰
	 * @param comNum
	 * @return
	 */
	List<TUserResources> selectListByComNum(String comNum);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RESOURCES
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RESOURCES
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    int insert(TUserResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RESOURCES
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    int insertSelective(TUserResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RESOURCES
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    TUserResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RESOURCES
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    int updateByPrimaryKeySelective(TUserResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RESOURCES
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    int updateByPrimaryKey(TUserResources record);
}