package rest.mybatis.model.misModel;

import java.io.Serializable;

public class TResources implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.ID
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.RESOURCE_AUTH
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private String resourceAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.RESOURCE_TYPE
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.BELONGS
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private String belongs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.SUB_BELONGS
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private String subBelongs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.INDEX_NUM
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private Integer indexNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.RESOURCE_NAME
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCES.PROTECTED_DES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    private String protectedDes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.ID
     *
     * @return the value of T_RESOURCES.ID
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.ID
     *
     * @param id the value for T_RESOURCES.ID
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.RESOURCE_AUTH
     *
     * @return the value of T_RESOURCES.RESOURCE_AUTH
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public String getResourceAuth() {
        return resourceAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.RESOURCE_AUTH
     *
     * @param resourceAuth the value for T_RESOURCES.RESOURCE_AUTH
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setResourceAuth(String resourceAuth) {
        this.resourceAuth = resourceAuth == null ? null : resourceAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.RESOURCE_TYPE
     *
     * @return the value of T_RESOURCES.RESOURCE_TYPE
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.RESOURCE_TYPE
     *
     * @param resourceType the value for T_RESOURCES.RESOURCE_TYPE
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.BELONGS
     *
     * @return the value of T_RESOURCES.BELONGS
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public String getBelongs() {
        return belongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.BELONGS
     *
     * @param belongs the value for T_RESOURCES.BELONGS
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setBelongs(String belongs) {
        this.belongs = belongs == null ? null : belongs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.SUB_BELONGS
     *
     * @return the value of T_RESOURCES.SUB_BELONGS
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public String getSubBelongs() {
        return subBelongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.SUB_BELONGS
     *
     * @param subBelongs the value for T_RESOURCES.SUB_BELONGS
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setSubBelongs(String subBelongs) {
        this.subBelongs = subBelongs == null ? null : subBelongs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.INDEX_NUM
     *
     * @return the value of T_RESOURCES.INDEX_NUM
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public Integer getIndexNum() {
        return indexNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.INDEX_NUM
     *
     * @param indexNum the value for T_RESOURCES.INDEX_NUM
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setIndexNum(Integer indexNum) {
        this.indexNum = indexNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.RESOURCE_NAME
     *
     * @return the value of T_RESOURCES.RESOURCE_NAME
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.RESOURCE_NAME
     *
     * @param resourceName the value for T_RESOURCES.RESOURCE_NAME
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCES.PROTECTED_DES
     *
     * @return the value of T_RESOURCES.PROTECTED_DES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public String getProtectedDes() {
        return protectedDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCES.PROTECTED_DES
     *
     * @param protectedDes the value for T_RESOURCES.PROTECTED_DES
     *
     * @mbggenerated Thu Dec 14 14:09:20 CST 2017
     */
    public void setProtectedDes(String protectedDes) {
        this.protectedDes = protectedDes == null ? null : protectedDes.trim();
    }
}