package rest.mybatis.model.misModel;

import java.io.Serializable;

public class TUserResources implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_RESOURCES.ID
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_RESOURCES.COM_NUM
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    private String comNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_RESOURCES.RESOURCE
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    private String resource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_RESOURCES.ID
     *
     * @return the value of T_USER_RESOURCES.ID
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_RESOURCES.ID
     *
     * @param id the value for T_USER_RESOURCES.ID
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_RESOURCES.COM_NUM
     *
     * @return the value of T_USER_RESOURCES.COM_NUM
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    public String getComNum() {
        return comNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_RESOURCES.COM_NUM
     *
     * @param comNum the value for T_USER_RESOURCES.COM_NUM
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    public void setComNum(String comNum) {
        this.comNum = comNum == null ? null : comNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_RESOURCES.RESOURCE
     *
     * @return the value of T_USER_RESOURCES.RESOURCE
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_RESOURCES.RESOURCE
     *
     * @param resource the value for T_USER_RESOURCES.RESOURCE
     *
     * @mbggenerated Thu Dec 14 13:47:08 CST 2017
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }
}